### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [zysite/biaffine-parser#12]
你好，很抱歉多次打扰你！请问你的代码中做了几处更改后，在执行过程中报了下面两个错误：

- corpus.py

```
Sentence = namedtuple(typename='Sentence',
                      field_names=['ID', 'FORM', 'LEMMA', 'CPOS',
                                   'POS', 'FEATS', 'HEAD', 'DEPREL',
                                   'PHEAD', 'PDEPREL'],
                      defaults=[None]*10)
```  
上述对于Sentence的声明中加入了defaults，在运行中会报错：
```

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from parser.cmds import Evaluate, Predict, Train
  File "/data/lxiao/workspace/biaffine-parser/parser/cmds/__init__.py", line 3, in <module>
    from .evaluate import Evaluate
  File "/data/lxiao/workspace/biaffine-parser/parser/cmds/evaluate.py", line 4, in <module>
    from parser.utils import Corpus
  File "/data/lxiao/workspace/biaffine-parser/parser/utils/__init__.py", line 4, in <module>
    from .corpus import Corpus
  File "/data/lxiao/workspace/biaffine-parser/parser/utils/corpus.py", line 10, in <module>
    defaults=[None]*10)
TypeError: namedtuple() got an unexpected keyword argument 'defaults'

```

- 关于parser.py
```
Create the model
BiaffineParser(
  (pretrained): Embedding(355413, 300)
  (embed): Embedding(21118, 300)
  (tag_embed): Embedding(4, 100)
  (embed_dropout): IndependentDropout(p=0.33)
  (lstm): BiLSTM(
    (f_cells): ModuleList(
      (0): LSTMCell(400, 400)
      (1): LSTMCell(800, 400)
      (2): LSTMCell(800, 400)
    )
    (b_cells): ModuleList(
      (0): LSTMCell(400, 400)
      (1): LSTMCell(800, 400)
      (2): LSTMCell(800, 400)
    )
  )
  (lstm_dropout): SharedDropout(p=0.33, batch_first=True)
  (mlp_arc_h): MLP(
    (linear): Linear(in_features=800, out_features=500, bias=True)
    (activation): LeakyReLU(negative_slope=0.1)
    (dropout): SharedDropout(p=0.33, batch_first=True)
  )
  (mlp_arc_d): MLP(
    (linear): Linear(in_features=800, out_features=500, bias=True)
    (activation): LeakyReLU(negative_slope=0.1)
    (dropout): SharedDropout(p=0.33, batch_first=True)
  )
  (mlp_rel_h): MLP(
    (linear): Linear(in_features=800, out_features=100, bias=True)
    (activation): LeakyReLU(negative_slope=0.1)
    (dropout): SharedDropout(p=0.33, batch_first=True)
  )
  (mlp_rel_d): MLP(
    (linear): Linear(in_features=800, out_features=100, bias=True)
    (activation): LeakyReLU(negative_slope=0.1)
    (dropout): SharedDropout(p=0.33, batch_first=True)
  )
  (arc_attn): Biaffine(n_in=500, n_out=1, bias_x=True)
  (rel_attn): Biaffine(n_in=100, n_out=3, bias_x=True, bias_y=True)
)

Traceback (most recent call last):
  File "run.py", line 52, in <module>
    cmd(config)
  File "/data/lxiao/workspace/biaffine-parser/parser/cmds/train.py", line 100, in __call__
    model.train(train_loader)
  File "/data/lxiao/workspace/biaffine-parser/parser/model.py", line 27, in train
    s_arc, s_rel = self.parser(words, tags)
  File "/home/user/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/lxiao/workspace/biaffine-parser/parser/parser.py", line 80, in forward
    x = self.lstm(x)
  File "/home/user/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/lxiao/workspace/biaffine-parser/parser/modules/bilstm.py", line 67, in forward
    x, batch_sizes = x
ValueError: too many values to unpack (expected 2)

```

**Comment by zysite** [comment]
>= python 3.7 
如果是完整的conll文件，可以去掉defaults

**Comment by xiaoxiaoAurora** [comment]
> python >= 3.7
> 如果是完整的conll文件，可以去掉defaults

嗯嗯，是版本的问题，很感谢你！

**Comment by zysite** [comment]
不客气
