### ISSUE TITLE
TypeError: namedtuple() got an unexpected keyword argument 'defaults'

### ISSUE THREAD

**Issue by iseesaw** [zysite/biaffine-parser#15]
```
[kyzhang@gpu12 biaffine-parser]$ python run.py train -h
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from parser.cmds import Evaluate, Predict, Train
  File "/users6/kyzhang/attempts/biaffine-parser/parser/cmds/__init__.py", line 3, in <module>
    from .evaluate import Evaluate
  File "/users6/kyzhang/attempts/biaffine-parser/parser/cmds/evaluate.py", line 5, in <module>
    from parser.cmds.cmd import CMD
  File "/users6/kyzhang/attempts/biaffine-parser/parser/cmds/cmd.py", line 4, in <module>
    from parser.utils import Embedding
  File "/users6/kyzhang/attempts/biaffine-parser/parser/utils/__init__.py", line 3, in <module>
    from . import corpus, data, field, fn, metric
  File "/users6/kyzhang/attempts/biaffine-parser/parser/utils/corpus.py", line 10, in <module>
    defaults=[None]*10)
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
```

**Comment by iseesaw** [comment]
Can't use under `Python 3.6` ???

**Comment by zysite** [comment]
Python 3.7 works.
Or if you do not want to do the prediction, just delete this line.

**Comment by iseesaw** [comment]
> Python 3.7 works.
> Or if you do not want to do the prediction, just delete this line.

Thanks.
